# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WNG3lFbc0KqODVrcNnCvBrqe3LjmocCU
"""

print("Hello World!")